---
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: conventions-spring-boot
  labels:
    app.kadras.io/framework: spring-boot
data:
  properties: |
    server:
      port: 8080
      shutdown: graceful
      lifecycle:
        timeout-per-shutdown-phase: 24s
    spring:
      profiles:
        active: prod
    management:
      server:
        port: 8081
      endpoints:
        web:
          base-path: /actuator
      endpoint:
        health:
          probes:
            add-additional-paths: true
      health:
        probes:
          enabled: true
  livenessProbe:
    successThreshold: 1
    failureThreshold: 3
    httpGet:
      path: /livez
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
  readinessProbe:
    successThreshold: 1
    failureThreshold: 3
    httpGet:
      path: /readyz
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
  configVolumeMountPath: /workspace/config
