---
apiVersion: app.kadras.io/v1alpha1
kind: Workload
metadata:
  name: composer-assistant
spec:
  image: ghcr.io/thomasvitale/composer-assistant:f0d8e90220425b57d6339336d59c55cdf5fda788
  deployment:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /actuator/prometheus
      prometheus.io/port: "8080"
    env:
      - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
        value: http://tempo.observability-stack.svc.cluster.local:4318/v1/traces
