#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! This Secret will be populated by secretgen-controller with the credentials to authenticate
#! with the container registry from where to pull the images to deploy (if authentication is required).
#! Such credentials should grant read-only access to the private container registry.
#! Use cases: private registries or air-gapped scenarios.

#@ image_pull_secret_name = "canonical-registry-credentials"

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ image_pull_secret_name
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
