apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: ${{ values.name }}.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: ${{ values.name }}.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/${{ values.name }}/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: ${{ values.name }}.packages.kadras.io
spec:
  categories:
  - ${{ values.category }}
  displayName: ${{ values.name }}
  longDescription: ${{ values.description }}
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: ${{ values.description }}
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/${{ values.name }}
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: ${{ values.name }}
spec:
  packageRef:
    refName: ${{ values.name }}.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
