spring:
  application:
    name: composer-assistant
  profiles:
    active: local

langchain4j:
  ollama:
    enabled: false
  openai:
    client:
      api-key: ${OPENAI_API_KEY}

management:
  tracing:
    enabled: false
