---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: kadras-system
spec:
  dependsOn:
    - name: supply-chains-compositions
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: gitops-configurer
  path: ./gitops/apps/staging
  prune: true
  wait: true
